model_params:
  alg: ppo2
  network: impala_cnn_lstm

training_params:
  num_timesteps: 1e11
  save_path: None
  play: False
  seed: None
  num_env: None

env_params:
  env: VizDoomTrack2-v0
  env_type: custom
  # frame_stack: True
